// <auto-generated />
namespace mostaan.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class chatDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chatDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202106040614235_chatDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
